#!/bin/bash
set -e
PLUGINS_ENDPOINT=http://updates.jenkins-ci.org/latest/

DATA=/var/lib/jenkins
CONF_FOLDER=/root
mkdir -p $DATA/plugins
if find $DATA/plugins -maxdepth 0 -empty | read v; then
	(cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/active-directory.hpi)
	(cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/greenballs.hpi)
	(cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/credentials.hpi)
	(cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/ssh-credentials.hpi)
	(cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/ssh-agent.hpi)
	(cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/git-client.hpi)
	(cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/git.hpi)
	(cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/scm-api.hpi)
	(cd $DATA/plugins && wget --no-check-certificate $PLUGINS_ENDPOINT/postbuild-task.hpi)
	(mv $CONF_FOLDER/config.xml $DATA) 
        (mv $CONF_FOLDER/credentials.xml $DATA)
	(mv $CONF_FOLDER/hudson.tasks.Maven.xml $DATA)
fi


exec java -jar /opt/jenkins.war
